Generate new Django project
Razorr1996/dbp-task-manager pull request #1
Opened 2023-09-02 21:20 UTC by Razorr1996

2023-09-09 20:03 UTC, aleksandr-semenov-dbp requested changes

2023-09-09 20:03 UTC, aleksandr-semenov-dbp commented on Dockerfile
> +RUN curl -sSL https://install.python-poetry.org | python3 -
лучше зафиксировать актуальную версию поетри для повторяемости сборки

2023-09-09 23:21 UTC, Razorr1996 commented on Dockerfile
> +RUN curl -sSL https://install.python-poetry.org | python3 -
Теперь добавил POETRY_VERSION=1.6.1 в начало Dockerfile

2023-09-11 07:02 UTC, aleksandr-semenov-dbp approved these changes

2023-09-11 07:38 UTC, merged